on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        default: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: |
          dpkg -l
          echo ---------
          cat /etc/os-release
          echo ---------
          free
          echo ---------
          df -h
          echo ---------
          podman info
