on:
  workflow_dispatch:
    inputs:
      podman-images:
        description: 'podman image name'
        required: true

jobs:
  pull-and-package:
    runs-on: ubuntu-latest
    #if:  ${{ inputs.podman-images }} 
    steps:
    - name: Clean up data
      run: |
          podman system prune -a -f
          podman volume prune -f

    - name: Pull podman Image and Package
      run: |
        image="${{ inputs.podman-images }}"
        imageFile="${image//:/_}"
        imageFile="${imageFile//\//_}"
        podman pull "${image}"
        podman save "${image}" -o image.tar

    #- name: Compress files
    #  run: tar -czf amd64-images.tar.gz *-amd64.tar

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: podman-images-tar
        path: image.tar
        retention-days: 1

    - name: Clean up files
      run: |
        rm image.tar
